### PR TITLE
Added Grid Preview Functionality in Gallery View

### PR DESCRIPTION
**Pull request by Thisura98**
This pull request adds a lazy loading GridView, which is capable of displaying dynamic content.
Currently, only `FileTypeEnum.IMAGE` is supported. `FileTypeEnum.VIDEO` will be added soon.

This pull request resolves Issue #29.

### CODE REVIEW

**Comment by joaedwar** [comment]
@Thisura98 

**You are invited to our Community Meeting!**
Tella community meetings provide a virtual platform for those interested in Tella to meet, get to know each other, and learn about the uses, applications, and needs of Tella. Click here to [add the invite](http://evt.mx/yadcOPPH) to your calendar. You can join using this [link](https://us02web.zoom.us/j/89895144942). Please be sure to also follow us out on [Twitter](https://twitter.com/Tella_app/status/1318084407757049858). Hope to see you there!

**Comment by Raph33** [comment]
@Thisura98 there are conflicts from the other PRs we recently merged. Could you take a look at the latest version of the code and make fixes?

**Comment by Thisura98** [comment]
Sure @Raph33! Will take a look in the next few hours.

**Comment by Thisura98** [comment]
@Raph33 hello again, hope you all are doing great! I merged the recent PRs so there shouldn't be any conflicts now.

**Comment by ahlem-jarrar** [comment]
Hello @Thisura98, project do not compile with the latest commit, can you please check the problem ?

**Comment by Thisura98** [comment]
Hi @ahlem-jarrar! The project compiled for me on Xcode 12.0 (see below screenshot). Can you please let me know what error you are receiving? It might have to do with mixed up development teams, since I tested the app on a physical device. In any case will be glad to help to sort it out 🙂

Screenshot 2020-10-27 at 07 31 28

**Comment by ahlem-jarrar** [comment]
I'm trying to compile it with xcode 11.6, maybe I have to update it, I'll give it a try.

Capture d’écran 2020-10-27 à 09 42 41

**Comment by Raph33** [comment]
On my phone, the thumbnails for photos aren't being displayed

**Comment by Thisura98** [comment]
Dear @Raph33,

It has been a while and I apologize for not keeping you updated. I did not have the motivation to get back into this project before, but I would like to see this feature through going forward - if you still accept me working on this.

I re-visited my code from the repo and added new images snapped from the Camera. Following is what I see in the "Grid View" mode.

<image src="https://user-images.githubusercontent.com/16175314/105599875-a6487a00-5dba-11eb-8049-ef5fffccb22b.PNG" height="600"/>

There are 4 items items in the Gallery named as follows.

- Xf0c0WBQ.png
- gnZCSSei6.pdf
- 5AaX62Pw.png
- jokX79f2.png

Their previews are extracted in a background thread so the main UI thread is not blocked. In an ideal world, these previews would be cached. However, this would require the cached files be saved somewhere on the device - which leaks information. I am not sure the direction to take regarding the caching. 

I suspect there is an issue with this step that prevents the previews from correctly created - because it looks like the aspect ratio of the actual images are being preserved for whatever reason (see the middle image on the last row in the photo you provided).

I would like to help in resolving this current issue. It is possible that your team made changes to my original code while getting it to work in your development environment.

If there are any changes, kindly provide the modified files through an attached ZIP or a new branch in the repo. Otherwise if there are no changes, it would be helpful to have one of the erroneous images you tested with. I have attached below a ZIP of one of the images I tried in my build, please check if you are able to preview and display the image within Tella.

[tested-image-1.zip](https://github.com/Horizontal-org/Tella-iOS/files/5860399/tested-image-1.zip)

**Pull request closed without merging**
