### PR TITLE
Remove "Collect" button from homescreen

### LINKED ISSUE #30: Remove "Collect" button from homescreen
V1.0 of the app will not include support for data-collection. The "Collect" button on the homescreen should be removed.

### PR DESCRIPTION
**Pull request by subdan**
Closes #30

### CODE REVIEW

**Comment by subdan** [comment]
Could you please mark my PR as hacktoberfest-accepted? https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by Raph33** [comment]
@subdan done

**Comment by joaedwar** [comment]
@Raph33 Is this okay to merge?

**Comment by joaedwar** [comment]
@subdan 

**You are invited to our Community Meeting!**
Tella community meetings provide a virtual platform for those interested in Tella to meet, get to know each other, and learn about the uses, applications, and needs of Tella. Click here to [add the invite](http://evt.mx/yadcOPPH) to your calendar. You can join using this [link](https://us02web.zoom.us/j/89895144942). Please be sure to also follow us out on [Twitter](https://twitter.com/Tella_app/status/1318084407757049858). Hope to see you there!

**Pull request closed without merging**
