### PR TITLE
Adds an audio recorder feature

### PR DESCRIPTION
**Pull request by pastre**

### CODE REVIEW

**Comment by joaedwar** [comment]
**You are invited to our Community Meeting!**
Tella community meetings provide a virtual platform for those interested in Tella to meet, get to know each other, and learn about the uses, applications, and needs of Tella. The event is scheduled for **Thursday, Oct 22 @ 2 GMT**. Click here to [add the invite](http://evt.mx/yadcOPPH) to your calendar. You can join using this [link](https://us02web.zoom.us/j/89895144942). Please be sure to also follow us out on [Twitter](https://twitter.com/Tella_app/status/1318084407757049858). Hope to see you there!

**Comment by Raph33** [comment]
@pastre the record feature looks great!! 
However, there's been some conflicts from the other PRs we recently merged. Could you take a look at the latest version of the code and make fixes?

**Comment by pastre** [comment]
Yeah, sure, surry for the late response

**Comment by pastre** [comment]
@Raph33 should be fixed

**Comment by Raph33** [comment]
That was definitely not a late response @pastre :) thank you, it's looking good!

**Pull request merged**
